import { describe, it } from "bdd";
import { expect } from "expect";
import { aoc_24_08 } from "./day08.ts";

describe("2024 day8 part 1", () => {
  it("solves the puzzle", () => {
    expect(aoc_24_08(puzzleInput || sampleInput).size).toEqual(14);
  });
});

const sampleInput = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

const puzzleInput = ``;
